default_install_hook_types:
  - pre-commit
  - commit-msg
minimum_pre_commit_version: "4.0.0"
repos:
  # general pre-commit hooks, valid for the whole repository
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [--strict]


  # pre-commit hooks for the Python SDK
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff-check
        files: ^sdk/python/hydraidepy
        args: [--config, sdk/python/hydraidepy/pyproject.toml, --extend-select, I, --fix]
      - id: ruff-format
        files: ^sdk/python/hydraidepy
        args: [--config, sdk/python/hydraidepy/pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        pass_filenames: false
        args: [sdk/python/hydraidepy/., --strict, --ignore-missing-imports, --config-file, sdk/python/hydraidepy/pyproject.toml]
        files: ^sdk/python/hydraidepy
