version: "3.8"

services:
  hydraide-server:
    image: ghcr.io/hydraide/hydraide:latest
    ports:
      - "4900:4444"  # HostPort:ContainerPort – gRPC port to expose
    environment:
      - LOG_LEVEL=info  # Log level: trace | debug | info | warn | error
      - LOG_TIME_FORMAT=2006-01-02T15:04:05Z07:00  # Go time format for logs
      - SYSTEM_RESOURCE_LOGGING=false  # Enable system metrics logging (goroutines, memory)
      - GRAYLOG_ENABLED=false  # Enable external logging to Graylog (true/false)
      - GRAYLOG_SERVER=your.graylog.host:5140  # Only required if GRAYLOG_ENABLED=true
      - GRAYLOG_SERVICE_NAME=hydraide-swarm-node  # Custom name per instance for logs if GRAYLOG_ENABLED=true
      - GRPC_MAX_MESSAGE_SIZE=5368709120  # Max gRPC payload (5GB)
      - GRPC_SERVER_ERROR_LOGGING=true  # Log internal GRPC errors (useful for debugging)
      - HYDRAIDE_DEFAULT_CLOSE_AFTER_IDLE=10  # Close idle Swamps after 10s
      - HYDRAIDE_DEFAULT_WRITE_INTERVAL=5  # Write Swamps to disk every 5s
      - HYDRAIDE_DEFAULT_FILE_SIZE=8192  # Chunk size in bytes (matches ZFS block size)
    volumes:
      - /your/path/certificate:/hydraide/certificate  # Must contain server.crt and server.key before starting the server
      - /your/path/settings:/hydraide/settings        # Folder where server settings are initialized
      - /your/path/data:/hydraide/data                # Folder for all Swamp data
    stop_grace_period: 10m  # Required for clean shutdown and data flush
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4445/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1  # Only 1 replica allowed per data volume to prevent file corruption
      placement:
        constraints:
          - node.hostname == hydra-node-name  # Replace with the actual node name
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
